services:
    comment.block.list_comments:
        class: "CommentBundle\\Block\\ListCommentBlockService"
        arguments:
          - comment.block.list_comments
          - '@templating'
          - '@app.entity_manager'
        tags:
          - { name: sonata.block }

    comment.block.add_comment:
        class: "CommentBundle\\Block\\AddCommentBlockService"
        arguments:
          - comment.block.add_comment
          - '@templating'
          - '@app.entity_manager'
          - '@request_stack'
        tags:
          - { name: sonata.block }

    comment.block.list_swaps:
        class: "CommentBundle\\Block\\ListSwapBlockService"
        arguments:
            - comment.block.list_swaps
            - '@templating'
            - '@app.entity_manager'
        tags:
            - { name: sonata.block }

    comment.block.add_swap:
        class: "CommentBundle\\Block\\AddSwapBlockService"
        arguments:
            - comment.block.add_swap
            - '@templating'
            - '@app.entity_manager'
            - '@request_stack'
        tags:
            - { name: sonata.block }