services:
    comment.block.list_comments:
        class: "CommentBundle\\Block\\ListCommentBlockService"
        arguments:
          - comment.block.list_comments
          - '@templating'
          - '@app.entity_manager'
        tags:
          - { name: sonata.block }

    comment.block.add_comment:
        class: "CommentBundle\\Block\\AddCommentBlockService"
        arguments:
          - comment.block.add_comment
          - '@templating'
          - '@app.entity_manager'
          - '@request_stack'
        tags:
          - { name: sonata.block }