doctrine:
    dbal:
        server_version: '%server_version%'
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        enable_lazy_ghost_objects: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                report_fields_where_declared: true
                auto_mapping: true
                mappings:
                    SonataPageBundle: ~
                dql:
                    numeric_functions:
                        rand: DoctrineExtensions\Query\Mysql\Rand