twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locales_list: '%locales%'
        company_name: '%company_name%'
    paths:
        '%kernel.project_dir%/templates/app':         App
        '%kernel.project_dir%/templates/article':     Article
        '%kernel.project_dir%/templates/comment':     Comment
        '%kernel.project_dir%/templates/information': Information
        '%kernel.project_dir%/templates/main_image':  MainImage
        '%kernel.project_dir%/templates/media':       Media
        '%kernel.project_dir%/templates/order':       Order
        '%kernel.project_dir%/templates/page':        Page
        '%kernel.project_dir%/templates/product':     Product
        '%kernel.project_dir%/templates/share':       Share
        '%kernel.project_dir%/templates/wheel_spin':  WheelSpin
        '%kernel.project_dir%/templates/admin':       Admin
    form_themes:
        - '@Admin/Form/fields.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'