services:
    share.block.tag_list:
        class: "ShareBundle\\Block\\ListTagsBlockService"
        arguments:
          - share.block.tag_list
          - '@templating'
          - '@?doctrine'
        tags:
          - { name: sonata.block }

    share.block.author_list:
        class: "ShareBundle\\Block\\ListAuthorsBlockService"
        arguments:
          - share.block.author_list
          - '@templating'
          - '@?doctrine'
        tags:
          - { name: sonata.block }

    share.block.stones:
        class: "ShareBundle\\Block\\StonesBlockService"
        arguments:
            - share.block.stones
            - '@templating'
            - '@?doctrine'
        tags:
            - { name: sonata.block }

    share.block.zodiac:
        class: "ShareBundle\\Block\\ZodiacBlockService"
        arguments:
            - share.block.zodiac
            - '@templating'
            - '@?doctrine'
        tags:
            - { name: sonata.block }