# genre ========================================================
genre_list:
    path: /genres
    defaults:
        _controller: GenreBundle:Genre:list

genre_books:
    path: /genres/{genre}
    defaults:
        _controller: GenreBundle:Genre:listBook
    requirements:
        genre: "([a-zA-Z\\-0-9\\_]+)?"

sub_genre_books:
    path: /genres/{genre}/{sub_genre}
    defaults:
        _controller: GenreBundle:Genre:listBook
    requirements:
        genre: "([a-zA-Z\\-0-9\\_]+)?"
        sub_genre: "([a-zA-Z\\-0-9\\_]+)?"