services:
    information.block.info:
        class: InformationBundle\Block\InformationBlockService
        arguments:
          - '@twig'
          - '@app.entity_manager'
        tags:
          - { name: sonata.block }
