services:
    sonata.admin.book:
        class: BookBundle\Admin\BookAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "group.book", label: "group.book_editor" }
        arguments:
          - ~
          - BookBundle\Entity\Book
          - BookBundle:BookAdmin
        calls:
          - [ setTranslationDomain, [BookBundle] ]
          - [ setTemplate, ['edit', 'BookBundle:Admin:edit.html.twig'] ]
          - [ setEntityManager, ['@app.entity_manager'] ]

    sonata.admin.book_has_files:
        class: BookBundle\Admin\BookHasFileAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'group.book', label: "group.book_has_file_editor", show_in_dashboard: false }
        arguments:
          - ~
          - BookBundle\Entity\BookHasFile
          - ~
        calls:
          - [ setTranslationDomain, [BookBundle] ]

    sonata.admin.book_has_related:
        class: BookBundle\Admin\BookHasRelatedAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'group.book', label: "group.book_has_related", show_in_dashboard: false }
        arguments:
          - ~
          - "BookBundle\\Entity\\BookHasRelated"
          - ~
        calls:
          - [ setTranslationDomain, [BookBundle] ]

    sonata.admin.book_info_download:
      class: BookBundle\Admin\BookInfoDownloadAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'group.book', label: "group.book_info_download"}
      arguments:
        - ~
        - BookBundle\Entity\BookInfoDownload
        - ~
      calls:
        - [ setTranslationDomain, [BookBundle] ]

    sonata.admin.book_info_view:
      class: BookBundle\Admin\BookInfoViewAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'group.book', label: "group.book_info_view"}
      arguments:
        - ~
        - BookBundle\Entity\BookInfoView
        - ~
      calls:
        - [ setTranslationDomain, [BookBundle] ]

    sonata.admin.book_collection:
      class: BookBundle\Admin\BookCollectionAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "group.book", label: "group.book_collection_editor" }
      arguments:
        - ~
        - BookBundle\Entity\BookCollection
        - ~
      calls:
        - [ setTranslationDomain, [BookBundle] ]

    sonata.admin.book_collection_has_book:
      class: BookBundle\Admin\BookCollectionHasBookAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'group.book', label: "group.book_collection_has_book_editor", show_in_dashboard: false }
      arguments:
        - ~
        - BookBundle\Entity\BookCollectionHasBook
        - ~
      calls:
        - [ setTranslationDomain, [BookBundle] ]