# books ========================================================
book_view:
    path: /book/{id}-{slug}
    defaults:
        _controller: BookBundle\Controller\BookController::viewAction
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"
        id: "\\d+"

book_list:
    path: /newbook
    defaults:
        _controller: BookBundle\Controller\BookController::listAction

inc_book_download:
    path: /inc_download/book
    defaults:
        _controller: BookBundle\Controller\BookController::incDownloadAction

year_books:
    path: /year/{year}
    defaults:
        _controller: BookBundle\Controller\BookController::yearListAction
    requirements:
        year: "\\d+"

book_download:
    path: /download/book_file/{file_id}
    defaults:
        _controller: BookBundle\Controller\BookController::downloadAction
    requirements:
        file_id: "\\d+"

collection_category:
    path: /collection/g_{genre}
    defaults:
        _controller: BookBundle\Controller\BookController::collectionListAction
    requirements:
        genre: "([a-zA-Z\\-0-9\\_]+)?"

collection_view:
    path: /collection/{slug}
    defaults:
        _controller: BookBundle\Controller\BookController::collectionAction
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

collection_list:
    path: /collection
    defaults:
        _controller: BookBundle\Controller\BookController::collectionListAction