services:
    book.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine', getManager]
        public: false

    book.helper.views:
        class: BookBundle\Helper\BookViewHelper
        arguments:
            - '@app.entity_manager'

#
#    book.repository.abstract:
#        factory: [ '@book.entity_manager', 'getRepository' ]
#        abstract: true
#
#    book.repository.book:
#        class: "\\BookBundle\\Entity\\BookRepository"
#        parent: book.repository.abstract
#        arguments:
#          - 'BookBundle:Book'
