services:
    main.block.image:
        class: MainImageBundle\Block\MainImageBlockService
        arguments:
          - main.block.image
          - '@templating'
          - '@app.entity_manager'
        tags:
          - { name: sonata.block }
