# comments ========================================================
last_comments:
    path: /last-comments
    defaults:
        _controller: CommentBundle:Comment:list

comment_vote:
    path: /comment/vote
    defaults:
        _controller: CommentBundle:Comment:commentVote
