services:
    article.entity_manager:
        class: "Doctrine\\ORM\\EntityManager"
        factory: [ '@doctrine', getManager ]
        public: false

    article.repository.abstract:
        factory: [ '@product.entity_manager', 'getRepository' ]
        abstract: true

    article.repository.product:
        class: "\\ArticleBundle\\Entity\\ArticleRepository"
        parent: article.repository.abstract
        arguments:
            - 'ArticleBundle:Article'
        calls:
            -   method: setLocale
                arguments: [ "@=service('request_stack').getCurrentRequest() ? service('request_stack').getCurrentRequest().getLocale() : null" ]

    article.shortcode.processor.read:
        class: "ArticleBundle\\Shortcode\\ReadProcessorService"
        arguments:
            - '@doctrine.orm.entity_manager'