sonata_intl:
    locale: ~
    timezone:
        default: Europe/Kiev
        service: ~
        detectors:
            - sonata.intl.timezone_detector.user
            - sonata.intl.timezone_detector.locale
