sonata_seo:
    encoding: UTF-8
    page:
        title: Naturalstones Jewerly - Изделия из натуральных камней
        default: sonata.seo.page.default
        metas: ~

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
