services:
    sonata.admin.media_file:
        class: MediaBundle\Admin\MediaFileAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.media", label: "group.media_file_editor" }
        arguments:
            - ~
            - MediaBundle\Entity\MediaFile
            - AdminBundle\Controller\CRUDController
        calls:
            - [ setTranslationDomain, [MediaBundle] ]
            - [ setTokenStorage, ['@security.token_storage'] ]

    sonata.admin.media_image:
        class: MediaBundle\Admin\MediaImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.media", label: "group.media_image_editor" }
        arguments:
            - ~
            - MediaBundle\Entity\MediaImage
            - MediaBundle\Controller\MediaAdminController
        calls:
            - [ setTranslationDomain, [MediaBundle] ]
            - [ setOptimizer, ['@app.image.optimizer'] ]
            - [ setTokenStorage, ['@security.token_storage'] ]

    sonata.admin.media_video:
        class: MediaBundle\Admin\MediaVideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.media", label: "group.media_video_editor" }
        arguments:
            - ~
            - MediaBundle\Entity\MediaVideo
            - AdminBundle\Controller\CRUDController
        calls:
            - [ setTranslationDomain, [ MediaBundle ] ]
            - [ setTokenStorage, ['@security.token_storage'] ]