services:
    product.block.list:
        class: ProductBundle\Block\ListProductBlockService
        arguments:
            - '@twig'
            - '@request_stack'
        calls:
            - [ setDoctrine, [ '@?doctrine' ] ]
            -
                - 'setAdmins'
                -
                    -
                        tag: '@?share.admin.tag'
                        category: '@?sonata.admin.product_category'
                        stone: '@?share.admin.stone'
                        colour: '@?share.admin.colour'
        tags:
            - { name: sonata.block }

    product.block.popular:
        class: ProductBundle\Block\PopularProductsBlockService
        arguments:
            - '@twig'
            - '@?doctrine'
        tags:
            - { name: sonata.block }

    product.block.viewed:
        class: ProductBundle\Block\ListViewedProductBlockService
        arguments:
            - '@twig'
            - '@?doctrine'
            - '@request_stack'
        tags:
            - { name: sonata.block }