# books ========================================================
product_list:
    path: /catalog/{slug}
    defaults:
        _controller: ProductBundle:Product:list
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

product_view:
    path: /product/{category}/{id}-{slug}
    defaults:
        _controller: ProductBundle:Product:view
    requirements:
        category: "([a-zA-Z\\-0-9\\_]+)?"
        slug: "([a-zA-Z\\-0-9\\_]+)?"
        id: "\\d+"
