# products ========================================================
product_who_list:
    path: /catalog/{who}
    defaults:
        _controller: ProductBundle:Product:listWho
    requirements:
        who: "man|woman"

product_tags_list:
    path: /catalog/tag-{slug}
    defaults:
        _controller: ProductBundle:Product:listTag
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

product_colour_list:
    path: /catalog/colour-{slug}
    defaults:
        _controller: ProductBundle:Product:listColour
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

product_stone_list:
    path: /catalog/stone-{slug}
    defaults:
        _controller: ProductBundle:Product:listStone
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

product_list:
    path: /catalog/{slug}
    defaults:
        _controller: ProductBundle:Product:list
    requirements:
        slug: "([a-zA-Z\\-0-9\\_]+)?"

product_view:
    path: /product/{category}/{id}-{slug}
    defaults:
        _controller: ProductBundle:Product:view
    requirements:
        category: "([a-zA-Z\\-0-9\\_]+)?"
        slug: "([a-zA-Z\\-0-9\\_]+)?"
        id: "\\d+"
