services:
    product.helper.views:
        class: ProductBundle\Helper\ProductViewHelper
        arguments:
            - '@app.entity_manager'

    product.router.helper:
        class: ProductBundle\Helper\ProductRouterHelper
        arguments:
            - '@router'

    product.entity_manager:
        class: "Doctrine\\ORM\\EntityManager"
        factory: [ '@doctrine', getManager ]
        public: false

    product.repository.abstract:
        factory: [ '@product.entity_manager', 'getRepository' ]
        abstract: true

    product.repository.product:
        class: "\\ProductBundle\\Entity\\ProductRepository"
        parent: product.repository.abstract
        arguments:
            - 'ArticleBundle:Article'
        calls:
            -   method: setLocale
                arguments: [ "@=service('request_stack').getCurrentRequest() ? service('request_stack').getCurrentRequest().getLocale() : null" ]