services:
    book.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine', getManager]
        public: false

    book.helper.views:
        class: BookBundle\Helper\BookViewHelper
        arguments:
            - '@app.entity_manager'

    product.router.helper:
        class: ProductBundle\Helper\ProductRouterHelper
        arguments:
            - '@router'
