services:
    product.helper.views:
        class: ProductBundle\Helper\ProductViewHelper
        arguments:
            - '@app.entity_manager'

    product.router.helper:
        class: ProductBundle\Helper\ProductRouterHelper
        arguments:
            - '@router'
