services:
    app.block.service.language_switcher:
        class: "AppBundle\\Block\\LanguageSwitcherBlockService"
        arguments:
            - app.block.service.language_switcher
            - '@templating'
            - '@request_stack'
            - '%locales%'
        tags:
            - { name: sonata.block }

    app.block.service.footer:
        class: "AppBundle\\Block\\FooterBlockService"
        arguments:
            - app.block.service.footer
            - '@templating'
        tags:
            - { name: sonata.block }

    app.block.service.header:
        class: "AppBundle\\Block\\HeaderBlockService"
        arguments:
            - app.block.service.header
            - '@templating'
            - '@app.entity_manager'
        tags:
            - { name: sonata.block }

    app.block.service.menu:
        class: "AppBundle\\Block\\MenuBlockService"
        arguments:
            - app.block.service.menu
            - '@templating'
            - '@app.entity_manager'
        tags:
            - { name: sonata.block }

    app.block.service.search:
        class: "AppBundle\\Block\\SearchBlockService"
        arguments:
            - app.block.service.search
            - '@templating'
            - '@app.entity_manager'
            - '@request_stack'
        tags:
            - { name: sonata.block }

    app.block.service.search_category:
        class: "AppBundle\\Block\\SearchCategoryBlockService"
        arguments:
            - app.block.service.search_category
            - '@templating'
            - '@app.entity_manager'
            - '@request_stack'
        tags:
            - { name: sonata.block }

    app.block.service.banner:
        class: "AppBundle\\Block\\BannerBlockService"
        arguments:
            - app.block.service.banner
            - '@templating'
        tags:
            - { name: sonata.block }

    app.block.service.feedback:
        class: "AppBundle\\Block\\FeedbackBlockService"
        arguments:
            - app.block.service.feedback
            - '@templating'
            - '@request_stack'
            - '@app.send_telegram'
        tags:
            - { name: sonata.block }

    app.block.service.get_state_value:
        class: "AppBundle\\Block\\GetStateValueBlockService"
        arguments:
            - app.block.service.get_state_value
            - '@templating'
        calls:
            - [ 'setSaveStateService', [ '@app.save.state.value' ] ]
        tags:
            - { name: sonata.block }

    app.block.service.breadcrumb:
        class: "AppBundle\\Block\\BreadcrumbBlockService"
        arguments:
            - app.block.service.breadcrumb
            - '@templating'
            - '@app.breadcrumb'
        tags:
            - { name: sonata.block }

    app.block.service.cart:
        class: AppBundle\Block\CartBlockService
        arguments:
            - app.block.service.cart
            - '@templating'
            - '@app.cart'
            - '@request_stack'
        tags:
            - { name: sonata.block }