parameters:
#    sonata.page.admin.site.class: "PageBundle\\Admin\\SiteAdmin"
#    sonata.page.admin.page.class: "PageBundle\\Admin\\PageAdmin"
#    sonata.page.manager.page.class: "PageBundle\\Entity\\PageManager"
#    sonata.page.site.selector.host.class: "PageBundle\\Site\\HostSiteSelector"
#    sonata.page.route.page.generator.class: "PageBundle\\Route\\RoutePageGenerator"

#    assetic.value_supplier.class: "AppBundle\\Services\\CustomValueSupplier"
#    security.acl.permission.map.class: "Sonata\\AdminBundle\\Security\\Acl\\Permission\\AdminPermissionMap"

services:
    app.kernel.locale.subscriber:
        class: AppBundle\EventSubscriber\LocaleSubscriber
        arguments: [ '@cmf_routing.router', '%kernel.default_locale%' ]
        # redundant if you're using autoconfigure
        tags: [ kernel.event_subscriber ]

    app.security.authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        public: false
        arguments:
            - "@router"
            - "@session"

#    session.handler.pdo:
#        class: "Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\PdoSessionHandler"
#        public: false
#        arguments:
#            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
#            - { db_username: "%database_user%", db_password: "%database_password%" }
#
    app.pagerfanta.view.default:
        class: "AppBundle\\Template\\DefaultView"
        arguments:
            - '@app.pagerfanta.template.default'
            - { proximity: 9 }
        tags: [{ name: pagerfanta.view, alias: default }]

    app.pagerfanta.template.default:
        class: "AppBundle\\Template\\PagerfantaTemplate"
        calls:
            - [ 'setTranslator', ['@translator']]
            - [ 'init', ['AppBundle'] ]

    app.entity_manager:
        class: "Doctrine\\ORM\\EntityManager"
        factory: ['@doctrine', getManager]
        public: false

    app.seo.updater:
        class: "AppBundle\\Services\\SeoUpdater"
        arguments:
            - '@sonata.page.cms_manager_selector'
            - '@sonata.seo.page'
            - '@request_stack'
            - '@translator'
            - '@router'
            - '@app.save.state.value'
            - '%route_locales%'
#
#    app.redis.cache:
#        class: "Doctrine\\Common\\Cache\\RedisCache"
#
#    app.redis.cache.key.decorator:
#        class: "AppBundle\\Services\\RedisCacheKeyDecorator"
#        arguments:
#            - '@app.redis.cache'
#        calls:
#            - [ setNamespace, ['%secret%:app:redis:cache']]
#            - [ connect, ['%redis_host%', '%redis_port%']]
#
#
#    app.imagine.helper:
#        class: "AppBundle\\Helper\\ImagineHelper"
#        calls:
#            - [ 'setLiipImagineExtension', ['@liip_imagine.twig.extension']]
#            - [ 'setMediaCdn', ['%media_cdn_host%']]

    app.save.state.value:
        class: AppBundle\Services\SaveStateValue

    app.breadcrumb:
        class: AppBundle\Services\BreadcrumbService

    app.send_telegram:
        class: AppBundle\Services\SendTelegramService
        arguments:
            - '@router'
            - '@product.router.helper'
            - '@app.entity_manager'
            - '@monolog.http_client'
            - '@app.order_message.builder'
        calls:
            - [ setContainer, [ '@service_container' ] ]

    app.cart:
        class: AppBundle\Services\Cart
        arguments:
            - '@session'
            - '@app.entity_manager'

    app.helper.encrypt:
        class: AppBundle\Helper\EncryptHelper

    app.image.optimizer:
        class: AppBundle\Services\ImageOptimizer
        calls:
            - [ setRequest, [ '@request_stack' ] ]
            - [ setContainer, ['@service_container']]

    app.order_message.builder:
        class: AppBundle\Builder\OrderMessageBuilder
        arguments:
            - '@product.router.helper'
