lexik_translation:
    fallback_locale: ["%locale%"]  # (required) default locale to use
    managed_locales: "%locales%"  # (required) locales that the bundle have to manage
    base_layout: "LexikTranslationBundle::layout.html.twig" # layout used with the translation edition template
#    use_yml_tree: false  # if "true" we will print a nice tree in the yml source files. It is a little slower.
    grid_input_type: text  # define field type used in the grid (text|textarea)
    grid_toggle_similar: false  # If "true", on the grid if a locale colunm is shown/hidden then similar locales
                                # columns will be shown/hidden too.
                                # So if the col "en" is shown/hidden all "en_XX" cols will be shown/hidden too.
                                # Not in the reverse order ("en_XX" clicked, no impact on "en")
    storage:
        type: orm  # where to store translations: "orm", "mongodb" or "propel"
        object_manager: ~  # The name of the entity / document manager which uses different connection
                           # (see: http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html)
                           # When using propel, this can be used to specify the propel connection name
    resources_registration:
        type: all  # resources type to register: "all", "files" or "database"
        managed_locales_only: true  # will only load resources for managed locales

    auto_cache_clean: false  # set to true to make the bundle automatically clear translations cache files
    auto_cache_clean_interval: 600

    dev_tools:
        enable: "%kernel.debug%"
        create_missing: false
        file_format: yml