services:
    wheel_spin.block.wheel_spinner:
        class: "WheelSpinBundle\\Block\\WheelSpinnerBlockService"
        arguments:
            - wheel_spin.block.wheel_spinner
            - '@templating'
            - '@app.entity_manager'
            - '@request_stack'
        tags:
            - { name: sonata.block }