services:
    wheel_spin.block.wheel_spinner:
        class: "WheelSpinBundle\\Block\\WheelSpinnerBlockService"
        arguments:
            - '@twig'
            - '@app.entity_manager'
            - '@request_stack'
            - '@AppBundle\Services\SendTelegramService'
        tags:
            - { name: sonata.block }
